from typing import Dict, Any
from agents.state import ReviewState
from agents.nodes.planner import llm_invoke

def run_synthesizer(state: ReviewState) -> dict:
    """
    Acts as the Lead Developer. Reviews all outputs from sub-agents,
    filters noise/hallucinations, groups related comments, and formats
    the final Markdown review to post on GitHub or locally.
    """
    diff = state.get("diff", "")
    
    # Collect available reports
    reports = []
    if state.get("bug_report"):
        reports.append(f"### Bug Detector Report\n{state['bug_report']}\n")
    if state.get("security_report"):
        reports.append(f"### Security Scanner Report\n{state['security_report']}\n")
    if state.get("style_report"):
        reports.append(f"### Style Checker Report\n{state['style_report']}\n")
    if state.get("test_suggestions"):
        reports.append(f"### Test Suggester Report\n{state['test_suggestions']}\n")
        
    combined_reports = "\n".join(reports)
    
    if not combined_reports.strip():
        return {"final_review": "No issues found by any agents. Looks good to merge!"}
        
    prompt = (
        "You are a Lead Software Engineer reviewing a Pull Request. "
        "Below are the reports generated by your specialized sub-agents. "
        "Synthesize these findings into a polished, professional Markdown review. "
        "Filter out contradictory or irrelevant hallucinations, consolidate similar points, "
        "and present actionable feedback clearly. Do not invent new bugs that the agents didn't find.\n\n"
        f"--- Diff ---\n{diff}\n\n"
        f"--- Agent Reports ---\n{combined_reports}\n\n"
        "Draft the final Markdown Review comment:"
    )
    
    try:
        msg = llm_invoke(prompt)
        return {"final_review": msg.content}
    except Exception as e:
        return {"final_review": f"Error running Synthesizer: {str(e)}\n\nRaw Reports:\n{combined_reports}"}
